### ISSUE TITLE
Open source PCB files?

### ISSUE THREAD

**Issue by kallisti5** [IAmOrion/BMW-iDrive-BLE-HID#1]
Any plans to open source the PCB files? I'd love to make one of these since they're no longer for sale.

**Comment by IAmOrion** [comment]
> Any plans to open source the PCB files? I'd love to make one of these since they're no longer for sale.

Where are you located? If you're in the UK I can post you one? I stopped selling because delivery was sketchy and unreliable due to covid-19.

I made the PCB in Fritzing (I only bothered with the PCB part, nothing else) - I will upload the Gerber files that can be used with JLCPCB later as well as the fritzing file

**Comment by IAmOrion** [comment]
Files now uploaded

**Comment by kallisti5** [comment]
Thanks! USA.   Want to do a Chevy Bolt EV -> MQTT thing and there aren't really any good ODB2 Featherwings.
Thanks for uploading!!!

**Comment by kallisti5** [comment]
For any other lurkers.. here's how much the boards cost at oshpark:
```
We detected a 2 layer board of 2.01 x 0.90 inches (51.0 x 22.9mm)
3 boards will cost $9.00 
```

**Comment by IAmOrion** [comment]
> For any other lurkers.. here's how much the boards cost at oshpark:
> 
> ```
> We detected a 2 layer board of 2.01 x 0.90 inches (51.0 x 22.9mm)
> 3 boards will cost $9.00 
> ```

Out of curiosity have you tried JLCPCB? That's who I used .  Although maybe oshpark is better for US customers I dunno.

**Comment by kallisti5** [comment]
I've used JLCPCB before, they aren't too bad.
OSHPark generally has faster shipping though. (They manufacture locally in the US)
