### ISSUE TITLE
Wakeup sequences identical for all iDrive Units?

### ISSUE THREAD

**Issue by maxupp** [IAmOrion/BMW-iDrive-BLE-HID#2]
Hey! I'm doing a bit of porting of your code to work on my CAN shield with this lib: https://github.com/autowp/arduino-mcp2515

Unfortunately I haven't been able to get my iDrive Controller to wake so far. From what I've seen I have the same control unit that you got working, so I'm wondering what I'm doing wrong here...

Could you tell me where you got the wakeup sequence codes from?
Thanks!

**Comment by JumpMaster** [comment]
Would be helpful to know what model number you have and what model number James has.  I've been looking at upgrading my non-touch version and have seen the following models for sale on ebay.

6829079 - Rounded buttons - 2016 - 4 pin
6839079 - 2016 - 4 pin
6844225 - Ceramic rounded buttons - 2017 - 4 pin

9299305 - 2012
9320288 - 2013 - 4 pin
9332285 - 2014
9350723 - 2014-2015 - 4 pin - (Known good - maxupp)
9350725 - Ceramic - 2014 - 4 pin
9350731 - 2014 (2010-2017? NBT)
9459630 - Ceramic silver rounded buttons - 2019 - 4 pin
9490069 - Rounded buttons - 2018 - 4 pin
9490075 - Rounded buttons - 2018
9866964 - Rounded buttons - 2017-2018 (13-18?) - 4 pin

**Comment by maxupp** [comment]
I was able to mostly work it out. In my case, the unit communicates at 1000KBp/s, which I haven't seen mentioned anywhere, I ended up bruteforcing all the combinations.

My unit apparently doesn't require an extensive wakeup system, I've been fine with the initial 273, followed by repeated polling with 501.

**Comment by JumpMaster** [comment]
That's good to hear. Could you share what model number you have please? Would be good to know a "known good" configuration.

**Comment by maxupp** [comment]
![image](https://user-images.githubusercontent.com/5763229/161999002-01dc89e9-25e1-4f9b-a7f2-06b4df03c3d1.png)

**Comment by JumpMaster** [comment]
Thanks. I've added (known good) to your module in the above table.
